automatically download youtube-dl and added few cosmetic stuff

diff --git a/mp3downloader b/mp3downloader
--- a/mp3downloader
+++ b/mp3downloader
@@ -10,23 +10,44 @@
 basedir="$(dirname $(readlink -f $0))"
 source ${basedir}/config
 
-if [[ ! -f ${basedir}/youtube-dl ]]; then
-  echo -e "${bold}${red}ERROR: Make sure latest youtube-dl script are in the same directory."
-  echo -e "Download from https://github.com/rg3/youtube-dl/#installation${nc}"
-  exit 99
+#if [[ ! -f ${basedir}/youtube-dl ]]; then
+#  echo -e "${bold}${red}ERROR: Make sure latest youtube-dl script are in the same directory."
+#  echo -e "Download from https://github.com/rg3/youtube-dl/#installation${nc}"
+#  exit 99
+#fi
+
+eval ${lines}
+
+if [[ ! -f ${basedir}/bin/youtube-dl ]]; then
+  echo -e "${bold}${green}INFO: ${yellow}youtube-dl binary is nowhere to be found. Will start downloading.."
+  echo -e ""
+  yt_binary="${basedir}/bin/youtube-dl"
+  mkdir -p ${basedir}/bin
+  curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ${yt_binary}
+  if [[ $? -ne 0 ]]; then
+    echo ; echo -e "${bold}${red}ERROR: ${yellow}Download failed. ${red}*Shot myself in the head.*"
+    exit 99
+  fi
+  chmod 755 ${yt_binary}
+  echo ; echo -e "${bold}${green}INFO: ${yellow}youtube-dl binary has successfully been downloaded.${nc}"
+  eval ${lines}
 fi
 
+youtube_dl="${basedir}/bin/youtube-dl"
+
 if [[ $# -eq 0 ]]; then
-  echo -e "${bold}${red}ERROR: Video or playlist URL required."
+  echo -e "${bold}${red}ERROR: ${yellow}Video or playlist URL required."
   echo -e ""
-  echo -e "Example:"
-  echo -e "Video URL    : https://www.youtube.com/watch?v=8h9e8gxm43s"
-  echo -e "Playlist URL : https://www.youtube.com/watch?list=RDEMIiz34w04aCC1LtxFCoM_EQ"
+  echo -e "${green}Example:"
+  echo -e "${green}Video URL    : https://www.youtube.com/watch?v=8h9e8gxm43s"
+  echo -e "${green}Playlist URL : https://www.youtube.com/watch?list=RDEMIiz34w04aCC1LtxFCoM_EQ${nc}"
+  eval ${lines}
   exit 99
 fi
 
 # Make sure youtube-dl is latest version
-youtube-dl -U
+${youtube_dl} -U
+eval ${lines}
 
 video=0
 playlist=0
@@ -65,18 +86,18 @@ fi
 
 if [[ $1 =~ list ]]; then
   read -p "Would you like to download the whole playlist? (y/N): "
+eval ${lines}
 fi
 
 if [[ "${REPLY,,}" =~ ^y ]]; then
-   # echo "youtube-dl -f 140 --yes-playlist $1"
-   # youtube-dl -f 140 --yes-playlist $1
-   youtube-dl --yes-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$1"
+   ${youtube_dl} --yes-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$1"
+eval ${lines}
 elif [[ "-z $REPLY" ]] || [[ "${REPLY,,}" =~ ^n ]]; then
-   # echo "youtube-dl -f 140 --no-playlist $1"
-   # youtube-dl -f 140 --no-playlist $1
-   youtube-dl --no-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$@"
+   ${youtube_dl} --no-playlist --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' "$@"
+eval ${lines}
 else
    echo
    echo -e "${bold}${red}Poor guy. You don't even know what you want in life!${nc}"
+   eval ${lines}
    exit 99
 fi
